security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
            App\Entity\User:
                algorithm: bcrypt

    providers:
        our_db_provider:
                    entity:
                        class: App\Entity\User
                        property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|fonts|assets|web)/
            security: false
            anonymous: ~
        main:
            anonymous: ~

            form_login:
                            login_path: login
                            check_path: login
                            default_target_path: admin
                            #csrf_token_generator: security.csrf.token_manager

            logout:
                            # The route name the user can go to in order to logout
                            path: security_logout
                            # The name of the route to redirect to after logging out
                            target: /admin
#
#    access_control:
#            # this is a catch-all for the admin area
#            # additional security lives in the controllers
#            - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }
            # activate different ways to authenticate
#            - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
#            - { path: '^/css/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
