framework:
    validation:
        cache: validator.mapping.cache.doctrine.apcu
#    serializer:
#        cache: serializer.mapping.cache.apcu

doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver:
               type: service
               id: doctrine.apcu.cache
        result_cache_driver: apcu
        second_level_cache:
            enabled: true