{
    "page"
:
    "1",
        "HotelServices"
:
    [{
        "HotelName": "Gladiola Star (Golden Sands) 4*",
        "HotelKey": "1921",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Standard",
        "RcKey": "44",
        "RdName": "DBL Standard",
        "RdKey": "304",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "BB",
        "PnKey": "23",
        "Cost": "275.4000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(30.60[Gladiola Star`18_EB10%-30.04.]*9) * 1 room = 275.40",
        "QuoteType": "0",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "http:\/\/www.gladiolastar.com\/",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "0,-1,-2",
        "ContractPrKey": "1922",
        "Rate": "EU"
    }, {
        "HotelName": "Green Park (Golden Sands) 3*+",
        "HotelKey": "1926",
        "RtCode": "APT",
        "RtKey": "58",
        "RcName": "1 bedroom APPART",
        "RcKey": "65",
        "RdName": "APT 1 bedroom APPART",
        "RdKey": "123",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "342.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(38.00[Ordinary_Green Park_01-16.06\/03-30.09]*9) * 1 room = 342.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "www.hotels-greenpark.com\/bg\/main.asp",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-3,-4,-5",
        "ContractPrKey": "1830",
        "Rate": "EU"
    }, {
        "HotelName": "Excelsior GS (Golden Sands) 4*",
        "HotelKey": "1919",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Standard",
        "RcKey": "44",
        "RdName": "DBL Standard",
        "RdKey": "304",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "372.3000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(49.30[Extr1_arr12.05-12.06\/07-28.09+EB15%b<30.04]*(7-2) + 62.90[Extr1_arr12.05-12.06\/07-28.09+EB15%b<30.04]*2) * 1 room = 372.30",
        "QuoteType": "0",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-9,-10,-11",
        "ContractPrKey": "1879",
        "Rate": "EU"
    }, {
        "HotelName": "Prestige Hotel &Aquapark (Golden Sands) 4*",
        "HotelKey": "1924",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Standard",
        "RcKey": "44",
        "RdName": "DBL Standard",
        "RdKey": "304",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "400.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(50.00[P&A`18_Extr_arr<05.06>14.09]*(9-1)) * 1 room = 400.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "prestigetours.bg",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-6,-7,-8",
        "ContractPrKey": "1853",
        "Rate": "EU"
    }, {
        "HotelName": "Doubletree by Hilton  (Golden Sands) 4*+",
        "HotelKey": "1932",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "BB",
        "PnKey": "23",
        "Cost": "446.4000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(49.60[Double Tree`18_EB20%-30.04.]*9) * 1 room = 446.40",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "http:\/\/doubletree1.hilton.com\/en_US\/dt\/hotel\/VARGSDI-DoubleTree-by-Hilton-Hotel-Varna-Golden-Sands\/accommodations.do",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-12,-13,-14",
        "ContractPrKey": "1834",
        "Rate": "EU"
    }, {
        "HotelName": "Helios Spa (Golden Sands) 4*",
        "HotelKey": "1931",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "662.4000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(73.60[Helios SPA`18_EB20%-30.04.]*9) * 1 room = 662.40",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "www.helios-spa.com",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-15,-16,-17",
        "ContractPrKey": "2465",
        "Rate": "EU"
    }, {
        "HotelName": "Kaliakra Palace (Golden Sands) 4*",
        "HotelKey": "2259",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "768.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(96.00[Kaliakra Palace'18_Extr-arr<07.06>&14.09]*(9-1)) * 1 room = 768.00",
        "QuoteType": "2",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-18,-19,-20",
        "ContractPrKey": "2604",
        "Rate": "EU"
    }, {
        "HotelName": "Melia Grand Hermitage (Golden Sands) 5*",
        "HotelKey": "1925",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "936.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(104.00[Ordinary`18_Melia GH-min.3 n.]*9) * 1 room = 936.00",
        "QuoteType": "2",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-21,-22,-23",
        "ContractPrKey": "1858",
        "Rate": "EU"
    }, {
        "HotelName": "Grifid hotels Arabella (Golden Sands) 4*",
        "HotelKey": "1927",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Deluxe Sea View",
        "RcKey": "84",
        "RdName": "DBL Deluxe Sea View",
        "RdKey": "355",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "1098.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(122.00[Ro_Ordinary_GH Arabela`18]*9) * 1 room = 1098.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-24,-25,-26",
        "ContractPrKey": "1825",
        "Rate": "EU"
    }, {
        "HotelName": "Grifid hotels Bolero (Golden Sands) 4*",
        "HotelKey": "1928",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Deluxe",
        "RcKey": "57",
        "RdName": "DBL Deluxe",
        "RdKey": "100",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "1134.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(126.00[Ro_Ordinary_Bolero`18]*9) * 1 room = 1134.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-27,-28,-29",
        "ContractPrKey": "1826",
        "Rate": "EU"
    }]
}


{
    "page"
:
    "1", "HotelServices"
:
    [{
        "HotelName": "Gladiola Star (Golden Sands) 4*",
        "HotelKey": "1921",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Standard",
        "RcKey": "44",
        "RdName": "DBL Standard",
        "RdKey": "304",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "BB",
        "PnKey": "23",
        "Cost": "275.4000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(30.60[Gladiola Star`18_EB10%-30.04.]*9) * 1 room = 275.40",
        "QuoteType": "0",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "http:\/\/www.gladiolastar.com\/",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "0,-1,-2",
        "ContractPrKey": "1922",
        "Rate": "EU"
    }, {
        "HotelName": "Green Park (Golden Sands) 3*+",
        "HotelKey": "1926",
        "RtCode": "APT",
        "RtKey": "58",
        "RcName": "1 bedroom APPART",
        "RcKey": "65",
        "RdName": "APT 1 bedroom APPART",
        "RdKey": "123",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "342.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(38.00[Ordinary_Green Park_01-16.06\/03-30.09]*9) * 1 room = 342.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "www.hotels-greenpark.com\/bg\/main.asp",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-3,-4,-5",
        "ContractPrKey": "1830",
        "Rate": "EU"
    }, {
        "HotelName": "Excelsior GS (Golden Sands) 4*",
        "HotelKey": "1919",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Standard",
        "RcKey": "44",
        "RdName": "DBL Standard",
        "RdKey": "304",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "372.3000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(49.30[Extr1_arr12.05-12.06\/07-28.09+EB15%b<30.04]*(7-2) + 62.90[Extr1_arr12.05-12.06\/07-28.09+EB15%b<30.04]*2) * 1 room = 372.30",
        "QuoteType": "0",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-9,-10,-11",
        "ContractPrKey": "1879",
        "Rate": "EU"
    }, {
        "HotelName": "Prestige Hotel &Aquapark (Golden Sands) 4*",
        "HotelKey": "1924",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Standard",
        "RcKey": "44",
        "RdName": "DBL Standard",
        "RdKey": "304",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "400.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(50.00[P&A`18_Extr_arr<05.06>14.09]*(9-1)) * 1 room = 400.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "prestigetours.bg",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-6,-7,-8",
        "ContractPrKey": "1853",
        "Rate": "EU"
    }, {
        "HotelName": "Doubletree by Hilton  (Golden Sands) 4*+",
        "HotelKey": "1932",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "BB",
        "PnKey": "23",
        "Cost": "446.4000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(49.60[Double Tree`18_EB20%-30.04.]*9) * 1 room = 446.40",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "http:\/\/doubletree1.hilton.com\/en_US\/dt\/hotel\/VARGSDI-DoubleTree-by-Hilton-Hotel-Varna-Golden-Sands\/accommodations.do",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-12,-13,-14",
        "ContractPrKey": "1834",
        "Rate": "EU"
    }, {
        "HotelName": "Helios Spa (Golden Sands) 4*",
        "HotelKey": "1931",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "662.4000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(73.60[Helios SPA`18_EB20%-30.04.]*9) * 1 room = 662.40",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": "www.helios-spa.com",
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-15,-16,-17",
        "ContractPrKey": "2465",
        "Rate": "EU"
    }, {
        "HotelName": "Kaliakra Palace (Golden Sands) 4*",
        "HotelKey": "2259",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "768.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(96.00[Kaliakra Palace'18_Extr-arr<07.06>&14.09]*(9-1)) * 1 room = 768.00",
        "QuoteType": "2",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-18,-19,-20",
        "ContractPrKey": "2604",
        "Rate": "EU"
    }, {
        "HotelName": "Melia Grand Hermitage (Golden Sands) 5*",
        "HotelKey": "1925",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Park View",
        "RcKey": "41",
        "RdName": "DBL Park View",
        "RdKey": "187",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "AI",
        "PnKey": "26",
        "Cost": "936.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(104.00[Ordinary`18_Melia GH-min.3 n.]*9) * 1 room = 936.00",
        "QuoteType": "2",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-21,-22,-23",
        "ContractPrKey": "1858",
        "Rate": "EU"
    }, {
        "HotelName": "Grifid hotels Arabella (Golden Sands) 4*",
        "HotelKey": "1927",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Deluxe Sea View",
        "RcKey": "84",
        "RdName": "DBL Deluxe Sea View",
        "RdKey": "355",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "1098.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(122.00[Ro_Ordinary_GH Arabela`18]*9) * 1 room = 1098.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-24,-25,-26",
        "ContractPrKey": "1825",
        "Rate": "EU"
    }, {
        "HotelName": "Grifid hotels Bolero (Golden Sands) 4*",
        "HotelKey": "1928",
        "RtCode": "DBL",
        "RtKey": "56",
        "RcName": "Deluxe",
        "RcKey": "57",
        "RdName": "DBL Deluxe",
        "RdKey": "100",
        "AcName": "2Ad",
        "AcKey": "2220",
        "PnCode": "UAI",
        "PnKey": "27",
        "Cost": "1134.0000",
        "AddHotsCost": "13.8000",
        "DetailBrutto": "(126.00[Ro_Ordinary_Bolero`18]*9) * 1 room = 1134.00",
        "QuoteType": "1",
        "CountryKey": "4",
        "CityKey": "33",
        "CityName": "Golden Sands",
        "HotelWebSite": {},
        "TariffId": "0",
        "TariffName": "Ordinary",
        "TariffDescription": {},
        "AddHots": "-27,-28,-29",
        "ContractPrKey": "1826",
        "Rate": "EU"
    }]
}